server:
  port: 8081
wx:
  appID: wx7cc610023ca5b1c2
  appsecret: c6a602717ab10987b87e74327eb78e24
  templateId: IE_DQKnJcGkv9ZF7ssMAELVFYBA_ng6XzKETNO6GPIc
  #token获取
  tokenApi: https://api.weixin.qq.com/cgi-bin/token
  #获取用户列表
  userListApi: https://api.weixin.qq.com/cgi-bin/user/get
  #获取用户信息
  userInfoApi: https://api.weixin.qq.com/cgi-bin/user/info

#和风天气api
api:
  weatherApi: https://devapi.qweather.com/v7/weather/now/
  indicesApi: https://devapi.qweather.com/v7/indices/1d/
  cityid: 101040100
  cityname: 重庆
  #天气指数type
  #https://dev.qweather.com/docs/resource/indices-info/
  type: 1,3,5,16
  key: a3e94e6fc09940d5b5327213a7f4882b
yiyan:
  api: "https://v1.hitokoto.cn/?c=k&encode=text"

TimerTask:
  cron: 0 0 8 * * ?
spring:
  profiles:
    active: prod
  mail:
    host: smtp.qq.com
    port: 587
    username: 2578527296@qq.com
    from: 2578527296@qq.com
    #邮箱授权码
    password: kwejlsqlgjcvdjcc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: utf-8
#docker run --name pushinfo -p 8081:8081 -d pushinfo:1.0